import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // Vendored / generated UI is not linted: the LiveKit voice-agent kit
  // (the embedded Sofía widget) and the shadcn primitives are regenerated by
  // tooling, so hand-fixing lint there is churn. This keeps `npm run lint` a
  // meaningful gate for the code we actually own.
  globalIgnores([
    'dist',
    'dist-server',
    'src/components/agents-ui/**',
    'src/hooks/agents-ui/**',
    'src/components/ui/**',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
  },
])
